#pragma once
#include<vector>

struct VehiclePreview {
	std::wstring VName;
	char* VCode;
	char* TexDict;
	char* TexName;
};


static std::vector<VehiclePreview> Super{
{L"Pfister 811","Pfister811","lgm_dlc_executive1","pfister811"},
{L"Adder","Adder","lgm_default","adder"},
{L"Autarch","autarch","lgm_dlc_xmas2017","autarch_b"},
{L"Banshee 900R","Banshee2","lsc_jan2016","banshee2"},
{L"Bullet","Bullet","lgm_default","bullet"},
{L"Cheetah","Cheetah","lgm_default","cheetah"},
{L"Cyclone","cyclone","lgm_dlc_smuggler","cyclone"},
{L"Cyclone","cyclone","lgm_dlc_smuggler","cyclone"},
{L"Deveste 8","DEVESTE","lgm_dlc_arena","deveste"},
{L"Emperor ETR1","Sheava","lgm_dlc_stunt","sheava"},
{L"Emerus","emerus","lgm_dlc_vinewood","emerus"},
{L"Entity XXR","entity2","lgm_dlc_assault","entity2"},
{L"Entity XF","Entityxf","lgm_default","entityxf"},
{L"FMJ","Fmj","lgm_dlc_executive1","fmj"},
{L"Furia","furia","lgm_dlc_casinoheist","furia"},
{L"Progen GP1","gp1","lgm_dlc_specialraces","gp1"},
{L"Infernus","Infernus","sssa_default","infernus"},
{L"Itali GTB Custom","italigtb2","lsc_dlc_import_export","italigtb2"},
{L"Itali GTB","Italigtb","lsc_dlc_import_export","italigtb"},
{L"Krieger","krieger","lgm_dlc_vinewood","krieger"},
{L"Nero Custom","Nero2","lsc_dlc_import_export","nero2_b"},
{L"Nero","Nero","lsc_dlc_import_export","nero2_a"},
{L"Osiris","Osiris","lgm_dlc_luxe","Osiris"},
{L"Penetrator","Penetrator","lgm_dlc_importexport","penetrator"},
{L"Annis RE-7B","Le7b","lgm_dlc_stunt","le7b"},
{L"Reaper","Reaper","lgm_dlc_executive1","reaper"},
{L"Rocket Voltic","voltic2","candc_importexport","voltic2"},
{L"Annis S80RR","s80","lgm_dlc_vinewood","s80"},
{L"Ubermacht SC1","sc1","lgm_dlc_xmas2017","sc1_b"},
{L"Scramjet","Scramjet","candc_battle","scramjet"},
{L"Sultan RS","Sultanrs","lsc_jan2016","sultan2_a"},
{L"Progen T20","T20","lgm_dlc_luxe","t20"},
{L"Taipan","taipan","lgm_dlc_assault","taipan"},
{L"Tempesta","Tempesta","lgm_dlc_importexport","tempesta"},
{L"Tezeract","tezeract","lgm_dlc_assault","tezeract"},
{L"Thrax","thrax","lgm_dlc_vinewood","thrax"},
{L"Turismo R","turismor","lgm_dlc_business","turismor"},
{L"Tyrant","TYRANT","lgm_dlc_assault","tyrant"},
{L"Tyrus","Tyrus","lgm_dlc_stunt","tyrus"},
{L"Vacca","Vacca","lgm_default","vacca"},
{L"Vagner","Vagner","lgm_dlc_gunrunning","vagner"},
{L"Vigilante","Vigilante","candc_smuggler","vigilante"},
{L"Visione","visione","lgm_dlc_smuggler","visione"},
{L"Voltic","Voltic","lgm_default","voltic_tless"},
{L"Proto X80 ","Prototipo","lgm_dlc_executive1","prototipo"},
{L"Ocelot XA-21","xa21","lgm_dlc_gunrunning","xa21"},
{L"Zentorno","Zentorno","lgm_dlc_business2","zentorno"},
{L"Zorusso","zorrusso","lgm_dlc_vinewood","zorrusso"}
};
static std::vector<VehiclePreview> Sports{
{L"Albany Alpha","Alpha","lgm_dlc_business","alpha"},
{L"Banshee Topless","Banshee","lgm_dlc_business2","banshee_tless"},
{L"Dinka Blista","Blista2","sssa_dlc_mp_to_sp","blista2"},
{L"Grotti Bestia GTS","Bestiagts","lgm_dlc_executive1","bestiagts"},
{L"Dinka Blista(GO GO Monkey)","blista3","",""},
{L"Bravado Buffalo Sprunk","Buffalo2","sssa_dlc_hipster","buffalo"},
{L"Bravado Buffalo S ","Buffalo3","sssa_dlc_mp_to_sp","buffalo3"},
{L"Bravado Buffalo","Buffalo","sssa_dlc_hipster","buffalo"},
{L"Grotti Carbonizzare","Carbonizzare","lgm_default","carboniz"},
{L"Pfister Comet Retro Custom","Comet3","lsc_dlc_import_export","comet3"},
{L"Pfister Comet","Comet2","sssa_default","comet2"},
{L"Pfister Comet Safari","comet4","lgm_dlc_xmas2017","comet4_b"},
{L"Pfister Comet SR","comet5","lgm_dlc_xmas2017","comet5_b"},
{L"Invetero Coquette","Coquette","lgm_default","coquette"},
{L"Obey 8F Drafter","drafter","lgm_dlc_vinewood","drafter"},
{L"Declasse Drift Tampa","tampa2","sssa_dlc_stunt","tampa2"},
{L"Elegy RH8","Elegy2","lgm_default","elegy2"},
{L"Annis Elegy Retro Custom","Elegy","lsc_dlc_import_export","elegy"},
{L"Benefactor Feltzer","Feltzer2","",""},
{L"Formula PR4", "formula", "lgm_dlc_casinoheist", "formula"},
{L"Formula R88", "formula2", "lgm_dlc_casinoheist", "formula2"},
{L"Vapid Flash GT","flashgt","lgm_dlc_assault","flashgt"},
{L"Lampadati Furore GT","Furoregt","lgm_dlc_lts_creator","furore"},
{L"Schyster Fusilade","Fusilade","sssa_dlc_business2","fusilade"},
{L"Karin Futo","futo","sssa_dlc_battle","futo"},
{L"Vapid GB200","gb200","lgm_dlc_assault","gb200"},
{L"Declasse Hotring Sabre","hotring","sssa_dlc_assault","hotring"},
{L"Overflod Imorgon","imorgon","lgm_dlc_casinoheist","imorgon"},
{L"Issi Sport","issi7","sssa_dlc_vinewood","issi7"},
{L"Grotti Itali GTO","ITALIGTO","lgm_dlc_arena","italigto"},
{L"Dinka Jester(Racecar)","jester2","sssa_dlc_christmas_2","jester2"},
{L"Dinka Jester Classic","jester3","lgm_dlc_assault","jester3"},
{L"Dinka Jester","Jester","lgm_dlc_business","jester"},
{L"Ocelot Jugular","jugular","lgm_dlc_vinewood","jugular"},
{L"Hijak Khamelion","Khamelion","",""},
{L"Lampadati Komoda","komoda","lgm_dlc_casinoheist","komoda"},
{L"Karin Kuruma(Armored)","kuruma2","sssa_dlc_heist","kuruma2"},
{L"Karin Kuruma","kuruma","sssa_dlc_heist","kuruma"},
{L"Ocelot Locust","locust","lgm_dlc_vinewood","locust"},
{L"Ocelot Lynx","lynx","lgm_dlc_stunt","lynx"},
{L"Dewbauchee Massacro (Race)","Massacro2","sssa_dlc_christmas_2","massacro2"},
{L"Dewbauchee Massacro","Massacro","lgm_dlc_business2","massacro"},
{L"Vysser Neo","neo","lgm_dlc_vinewood","neo"},
{L"Pfister Neon","neon","lgm_dlc_xmas2017","neon_b"},
{L"Obey 9F Cabrio","Ninef2","lgm_default","ninef2"},
{L"Obey 9F","Ninef","sssa_default","ninef"},
{L"Obey Omnis","Omnis","sssa_dlc_stunt","omnis"},
{L"Enus Paragon R","paragon","lgm_dlc_vinewood","paragon"},
{L"Enus Paragon R (Armored)","paragon2","lgm_dlc_vinewood","paragon"},
{L"Ocelot Pariah","pariah","lgm_dlc_xmas2017","pariah_b"},
{L"Maibatsu Penumbra","Penumbra","sssa_dlc_business2","penumbra"},
{L"Coil Raiden","raiden","lgm_dlc_xmas2017","raiden_b"},
{L"Dewbauchee Rapid GT Cabrio","rapidgt2","lgm_default","rapidgt2"},
{L"Dewbauchee Rapid GT","Rapidgt","lgm_default","rapidgt"},
{L"BF Raptor","raptor","lgm_dlc_biker","raptor"},
{L"Ubermacht Revolter","revolter","lgm_dlc_xmas2017","revolter_b"},
{L"Hijak Ruston","ruston","lgm_dlc_specialraces","ruston"},
{L"Benefactor Schafter LWB","schafter4","lgm_dlc_apartments","schafter4"},
{L"Benefactor Schafter V12","schafter3","lgm_dlc_apartments","schafter3"},
{L"Benefactor Schlagen GT","SCHLAGEN","lgm_dlc_arena","schlagen"},
{L"Benefactor Schwarter","schwarzer","sssa_default","schwarze"},
{L"Ubermacht Sentine Classic","sentinel3","sssa_dlc_xmas2017","sentinel3_b"},
{L"Dewbauchee Seven 70","Seven70","lgm_dlc_executive1","seven70"},
{L"Dewbauchee Specter","specter","lsc_dlc_import_export","specter2_a"},
{L"Dewbauchee Specter Custom","specter2","lsc_dlc_import_export","specter2_b"},
{L"Benefactor Streiter","streiter","lgm_dlc_xmas2017","streiter_b"},
{L"Dinka Sugoi","sugoi","sssa_dlc_casinoheist","sugoi"},
{L"Karin Sultan","Sultan","lsc_jan2016","sultan2_a"},
{L"Karin Sultan Classic","sultan2","sssa_dlc_casinoheist","sultan2"},
{L"Benefactor Surano","surano","lgm_default","surano_convertable"},
{L"Lampadati Tropos Rallye","tropos","sssa_dlc_stunt","tropos"},
{L"Albany V-STR","vstr","lgm_dlc_casinoheist","vstr"},
{L"Bravado Verlierer","Verlierer2","lgm_dlc_apartments","verlier"},
{L"Annis Future Shock ZR380","ZR3802","mba_vehicles","zr3802"},
{L"Annis Nightmare ZR380","ZR3803","mba_vehicles","zr3803"},
{L"Annis Apocalypse ZR380","ZR380","mba_vehicles","zr3801"}
};
static std::vector<VehiclePreview> SportsClassics{
{L"Ocelot Ardent","Ardent","candc_gunrunning","ardent"},
{L"Lampadati Casco","casco","lgm_dlc_heist","casco"},
{L"Rune Cheburek","cheburek","sssa_dlc_assault","cheburek"},
{L"Grotti Cheetah Classic","Cheetah2","lgm_dlc_gunrunning","cheetah2"},
{L"Invetero Coquette Classic","coquette2","lgm_dlc_pilot","coquette2"},
{L"Imponte Deluxo","deluxo","candc_xmas2017","deluxo_b"},
{L"Weeny Dynasty","dynasty","sssa_dlc_vinewood","dynasty"},
{L"Vulcar Fagaloa ","fagaloa","sssa_dlc_assault","fagaloa"},
{L"Grotti GT500","gt500","lgm_dlc_xmas2017","gt500_b"},
{L"Pegassi Infernus Classic","Infernus2","lgm_dlc_specialraces","infernus2"},
{L"Dewbauchee JB 700","jb700","lgm_default","jb700"},
{L"Dewbauchee JB 700W","jb7002","lgm_default","jb700"},
{L"Declasse Mamba","mamba","lgm_dlc_apartments","mamba"},
{L"Albany Manana","manana","",""},
{L"Lampadati Michelli GT","michelli","sssa_dlc_assault","michelli"},
{L"Pegassi Monroe","monroe","lgm_default","monroe"},
{L"Vulcar Nebula Turbo","nebula","sssa_dlc_vinewood","nebula"},
{L"Vapid Peyote","Peyote","",""},
{L"Lampadati Pigalle","pigalle","sssa_dlc_hipster","pigalle"},
{L"Dewbauchee Rapid GT Classic","rapidgt3","lgm_dlc_smuggler","rapidgt3"},
{L"Vapid Retinue Mk II","retinue2","sssa_dlc_casinoheist","retinue2"},
{L"Vapid Retinue","Retinue","",""},
{L"Vapid Retinue","Retinue","sssa_dlc_smuggler","retinue_b"},
{L"Albany Franken Strange","btype2","sssa_dlc_halloween","btype2"},
{L"Albany Roosevelt Valor","btype3","lgm_dlc_valentines2","roosevelt2"},
{L"Albany Roosevelt","btype","lgm_dlc_valentines","roosevelt"},
{L"Annis Savestra","savestra","lgm_dlc_xmas2017","savestra_b"},
{L"Grotti Stinger GT","stingergt","lgm_default","stingerg"},
{L"Grotti Stinger","stinger","lgm_default","stinger"},
{L"Benefactor Stirling GT","Feltzer3","lgm_dlc_luxe","feltzer3"},
{L"Ocelot Stromberg","stromberg","candc_xmas2017","stromberg_b"},
{L"Ocelot Swinger","Swinger","lgm_dlc_battle","swinger"},
{L"Pegassi Torero","torero","lgm_dlc_gunrunning","torero"},
{L"Declasse Tornado","Tornado","",""},
{L"Declasse Tornado Convertible","Tornado2","",""},
{L"Declasse Tornado Gang","Tornado3","",""},
{L"Declasse Tornado Convertible Gang","Tornado4","",""},
{L"Declasse Tornado Custom","Tornado5","lsc_lowrider2","tornado5_a"},
{L"Declasse Tornado Rat Rod","tornado6","sssa_dlc_biker","tornado6"},
{L"Grotti Turismo Classic","turismo2","lgm_dlc_specialraces","turismo2"},
{L"Lampadati Viseris","viseris","lgm_dlc_xmas2017","viseris_b"},
{L"Truffade Z-Type","ztype","lgm_default","ztype"},
{L"Karin 190z","z190","lgm_dlc_xmas2017","z190_b"},
{L"Ubermacht Zion Classic","zion3","sssa_dlc_vinewood","zion3"}
};
static std::vector<VehiclePreview> Coupes{
{L"Enus Cognoscenti Cabrio","cogcabrio","lgm_default","cogcabri"},
{L"Dewbauchee Exemplar","Exemplar","sssa_default","exemplar"},
{L"Ocelot F620","F620","sssa_dlc_business2","f620"},
{L"Lampadati Felon","Felon","sssa_default","felon"},
{L"Lampadati Felon GT","Felon2","sssa_default","felon2"},
{L"Ocelot Jackal","Jackal","sssa_dlc_heist","jackal"},
{L"Ubermacht Oracle","Oracle","sssa_default","oracle"},
{L"Ubermacht Oracle Mk2","oracle2","sssa_dlc_heist","oracle1"},
{L"Ubermacht Sentinel XS","Sentinel","sssa_dlc_business2","sentinel"},
{L"Ubermacht Sentinel","Sentinel2","sssa_dlc_business2","sentinel"},
{L"Enus Windsor","Windsor","lgm_dlc_luxe","windsor"},
{L"Enus Windsor Drop","Windsor2","",""},
{L"Ubermacht Zion","Zion","sssa_default","zion"},
{L"Ubermacht Zion Cabrio","Zion2","sssa_default","zion2"}
};
static std::vector<VehiclePreview> Muscle{
{L"Vapid Blade","Blade","sssa_dlc_hipster","blade"},
{L"Imponte Ruiner 2000","ruiner3","",""},
{L"Albany Buccaaneer Custom","Buccaneer2","lsc_default","buccaneer2_b"},
{L"Albany Buccaaneer","Buccaneer","lsc_default","buccaneer2_a"},
{L"Vapid Chino Custom","Chino2","lsc_default","chino2_a"},
{L"Vapid Chino","Chino","lgm_dlc_luxe","chino"},
{L"Vapid Clique","CLIQUE","lgm_dlc_arena","clique"},
{L"Invetero Coquette Blackfin","coquette3","lgm_dlc_luxe","coquette3"},
{L"Schyster Deviant","DEVIANT","lgm_dlc_arena","deviant"},
{L"Vapid Dominator GTX","dominator3","sssa_dlc_assault","dominator3"},
{L"Vapid Apocalypse Dominator","DOMINATOR4","mba_vehicles","dominato_c_1"},
{L"Vapid Future Shock Dominator","DOMINATOR5","mba_vehicles","dominato_c_2"},
{L"Vapid Nightmare Dominator","DOMINATOR6","mba_vehicles","dominato_c_3"},
{L"Vapid Dominator","Dominator","sssa_dlc_business2","dominato"},
{L"Imponte Dukes of Death","Dukes2","candc_default","dukes"},
{L"Imponte Dukes","Dukes","sssa_dlc_mp_to_sp","dukes"},
{L"Vapid Ellie","ellie","sssa_dlc_assault","ellie"},
{L"Williard Faction Custom Donk","Faction3","lsc_lowrider2","faction3_b"},
{L"Williard Faction Custom","Faction2","lsc_lowrider2","faction3_a"},
{L"Williard Faction","Faction","lsc_default","faction2_a"},
{L"Bravado Redwood Gauntlet","Gauntlet2","sssa_dlc_mp_to_sp","gauntlet2"},
{L"Bravado Gauntlet Classic Custom","gauntlet3","sssa_dlc_vinewood","gauntlet3"},
{L"Bravado Gauntlet Hellfire","gauntlet4","sssa_dlc_vinewood","gauntlet4"},
{L"Bravado Gauntlet","Gauntlet","sssa_default","gauntlet"},
{L"Albany Hermes","hermes","sssa_dlc_xmas2017","hermes_b"},
{L"Vapid Hotknife","Hotknife","lgm_default","hotknife"},
{L"Vapid Hustler","hustler","lgm_dlc_xmas2017","hustler_b"},
{L"Declasse Impaler","IMPALER","mba_vehicles","impaler"},
{L"Declasse Impaler","impaler","sssa_dlc_vinewood","impaler"},
{L"Declasse Apocalypse Impaler","IMPALER2","mba_vehicles","impaler_c_1"},
{L"Declasse Future Shock Impaler","IMPALER3","mba_vehicles","impaler_c_2"},
{L"Declasse Nightmare Impaler","IMPALER4","mba_vehicles","impaler_c_3"},
{L"Vapid Future Shock Imperator","IMPERATOR2","mba_vehicles","imperator2"},
{L"Vapid Nightmare Imperator","IMPERATOR3","mba_vehicles","imperator3"},
{L"Vapid Apocalypse Imperator","IMPERATOR","mba_vehicles","imperator1"},
{L"Albany Lurcher","lurcher","sssa_dlc_halloween","lurcher"},
{L"Declasse Moonbeam Custom","Moonbeam2","lsc_default","moonbeam2"},
{L"Declasse Moonbeam","Moonbeam","",""},
{L"Imponte Nightsade","nightshade","lgm_dlc_apartments","niteshad"},
{L"Vapid Peyote Gasser","peyote2","sssa_dlc_vinewood","peyote2"},
{L"Imponte Phoenix","phoenix","",""},
{L"Cheval Picador","picador","sssa_dlc_hipster","picador"},
{L"Vapid Pisswaser Dominator","Dominator2","sssa_dlc_mp_to_sp","dominator2"},
{L"Bravado Rat Loader","ratloader","sssa_dlc_valentines","rloader"},
{L"Bravado Rat truck","ratloader2","sssa_dlc_christmas_2","rloader2"},
{L"Imponte Ruiner 2000","ruiner2","candc_importexport","ruiner2"},
{L"Imponte Ruiner","ruiner","sssa_dlc_battle","ruiner"},
{L"Declasse Sabre Turbo","Sabregt","",""},
{L"Declasse Sabre Turbo Custom","Sabregt2","lsc_lowrider2","sabregt2_a"},
{L"Vapid Slamvan LostMC","Slamvan2","",""},
{L"Vapid Slamvan Custom","Slamvan3","lsc_lowrider2","slamvan3_b"},
{L"Vapid Apocalypse Slamvan ","SLAMVAN4","mba_vehicles","slamvan_c_1"},
{L"Vapid Future Shock Slamvan","SLAMVAN5","mba_vehicles","slamvan_c_2"},
{L"Vapid Nightmare Slamvan","SLAMVAN6","mba_vehicles","slamvan_c_3"},
{L"Vapid Slamvan","Slamvan","sssa_dlc_christmas_2","slamvan"},
{L"Declasse Burgershot Stallion","stalion2","sssa_dlc_mp_to_sp","stalion2"},
{L"Declasse Stallion","Stalion","sssa_dlc_mp_to_sp","stallion"},
{L"Declasse Weaponized Tampa","tampa3","candc_gunrunning","tampa3"},
{L"Declasse Tampa","Tampa","sssa_dlc_christmas_3","tampa"},
{L"Declasse Tulip","TULIP","sssa_dlc_arena","tulip"},
{L"Declasse Vamos","VAMOS","sssa_dlc_arena","vamos"},
{L"Declasse Vigero","Vigero","sssa_default","vigero"},
{L"Dundreary Virgo Classic Custom","Virgo2","lsc_lowrider2","virgo2_a"},
{L"Dundreary Virgo Classic","Virgo3","lsc_lowrider2","virgo2_b"},
{L"Dundreary Virgo","Virgo","lgm_dlc_luxe","virgo"},
{L"Declasse Voodoo Custom","Voodoo2","lsc_default","voodoo_b"},
{L"Declasse Voodoo","Voodoo","lsc_default","voodoo_a"},
{L"Declasse Yosemite","yosemite","sssa_dlc_xmas2017","yosemite_b"},
{L"Declasse Drift Yosemite","yosemite2","sssa_dlc_casinoheist","yosemite2"}
};
static std::vector<VehiclePreview> Offroad{
{L"BF Injection","bfinjection","sssa_default","bfinject"},
{L"BF Bifta","Bifta","sssa_default","bifta"},
{L"Nagasaki Hotrod Blazer","Blazer3","sssa_dlc_hipster","blazer3"},
{L"Nagasaki Blazer Aqua","Blazer5","candc_importexport","blazer5"},
{L"Nagasaki Blazer Lifeguard","Blazer2","",""},
{L"Nagasaki Blazer","Blazer","sssa_default","blazer"},
{L"Nagasaki Street Blazer","Blazer4","sssa_dlc_biker","blazer4"},
{L"Canis Bodhi","Bodhi2","sssa_default","bodhi2"},
{L"Coil Brawler","Brawler","lgm_dlc_luxe","brawler"},
{L"Benefactor Future Shock Bruiser","BRUISER2","mba_vehicles","bruiser_c_2"},
{L"Benefactor Nightmare Bruiser","BRUISER3","mba_vehicles","bruiser_c_3"},
{L"Benefactor Apocalypse Bruiser","BRUISER","mba_vehicles","bruiser_c_1"},
{L"Declasse Future Shock Brutus","BRUTUS2","mba_vehicles","brutus2"},
{L"Declasse Nightmare Brutus","BRUTUS3","mba_vehicles","brutus3"},
{L"Declasse Apocalypse Brutus","BRUTUS","mba_vehicles","brutus1"},
{L"Vapid Caracara 4x4","caracara2","sssa_dlc_vinewood","caracara2"},
{L"Vapid Caracara","caracara","candc_assault","caracara"},
{L"Benefactor Dubsta 6x6","Dubsta3","candc_default","dubsta3"},
{L"BF Dune FAV","Dune3","candc_gunrunning","dune3"},
{L"MTL Dune","Dune","sssa_default","dune"},
{L"BF Duneloader","Dloader","",""},
{L"Karin Everin","everon","sssa_dlc_casinoheist","everon"},
{L"Karin Freecrawler","Freecrawler","lgm_dlc_battle","freecrawler"},
{L"Annis Hellion","hellion","sssa_dlc_vinewood","hellion"},
{L"HVY Insurgent PickUp Custom","Insurgent3","",""},
{L"HVY Insurgent PickUp Custom","Insurgent3","ua_generic","ua_unlock_11"},
{L"HVY Insurgent","Insurgent","candc_default","insurgent"},
{L"HVY Insurgent PickUp","Insurgent2","candc_default","insurgent"},
{L"Canis Kalahari","Kalahari","sssa_default","kalahari"},
{L"Canis Kamacho","kamacho","sssa_dlc_xmas2017","kamacho_b"},
{L"Cheval Marshall","marshall","candc_default","marshall"},
{L"HVY Menacer","Menacer","candc_battle","menacer"},
{L"Canis Mesa (Merryweather)","Mesa3","candc_default","mesa3"},
{L"Bravado Apocalypse Sasquatch","MONSTER3","mba_vehicles","monster_c_1"},
{L"Bravado Future Shock Sasquatch","MONSTER4","mba_vehicles","monster_c_2"},
{L"Bravado Nightmare Sasquatch","MONSTER5","mba_vehicles","monster_c_3"},
{L"HVY Nightshark","nightshark","candc_gunrunning","nightshark"},
{L"Nagasaki Outlaw","outlaw","sssa_dlc_casinoheist","outlaw"},
{L"BF Dune Buggy","Dune4","",""},
{L"Dune","Dune5","candc_importexport","dune5"},
{L"Declasse Rancher XL","Rancherxl2","",""},
{L"Declasse Yosemite Rancher","Rancherxl","sssa_dlc_business","rancherx"},
{L"RC Bandito","RCBANDITO","sssa_dlc_arena","rcbandito"},
{L"Karin Rusty Rebel","Rebel2","sssa_dlc_hipster","rebel2"},
{L"Karin Rebel","Rebel","sssa_default","rebel"},
{L"Vapid Riata","riata","sssa_dlc_xmas2017","riata_b"},
{L"Vapid Sandking XL","Sandking","sssa_default","sandking_b"},
{L"Vapid Sandking SWB","Sandking2","sssa_default","sandkin_2b"},
{L"Dune2","Dune2","",""},
{L"Karin Technical modified edition","Technical3","",""},
{L"Karin Technical Aqua","Technical2","candc_importexport","technical2"},
{L"Karin Technical Custom","Technical3","ua_generic","ua_unlock_15"},
{L"Karin Technical","Technical","candc_default","technical"},
{L"Vapid Liberator","monster","candc_default","monster"},
{L"Vapid Desert Raid","TrophyTruck2","sssa_dlc_stunt","trophy2"},
{L"Vapid Trophy Truck","TrophyTruck","sssa_dlc_stunt","trophy"},
{L"Maxwell Vagrant","vagrant","sssa_dlc_casinoheist","vagrant"},
{L"Rune Zhaba","Zhaba","",""},

};
static std::vector<VehiclePreview> Motorcycles{
{L"Dinka Akuma","Akuma","sssa_default","akuma"},
{L"LCC Avarus","Avarus","sssa_dlc_biker","avarus"},
{L"Nagasaki BF400","BF400","sssa_dlc_stunt","bf400"},
{L"Western Bagger","Bagger","sssa_dlc_biker","bagger"},
{L"Pegassi Bati 801RR","BATI2","sssa_default","bati2"},
{L"Pegassi Bati 801","BATI","sssa_default","bati"},
{L"Nagasaki Carbon RS","CARBONRS","lgm_default","carbon"},
{L"Nagasaki Chimera","CHIMERA","sssa_dlc_biker","chimera"},
{L"Western Cliffhanger","CLIFFHANGER","sssa_dlc_stunt","cliffhanger"},
{L"Western Daemon Custom","DAEMON2","sssa_dlc_biker","daemon2"},
{L"Western Daemon","DAEMON","",""},
{L"Western Future Shock Deathbike","DEATHBIKE2","mba_vehicles","deathbike_c_2"},
{L"Western Nightmare Deathbike","DEATHBIKE3","mba_vehicles","deathbike_c_3"},
{L"Western Apocalypse Deathbike ","DEATHBIKE","mba_vehicles","deathbike_c_1"},
{L"Shitzu Defiler","DEFILER","sssa_dlc_biker","defiler"},
{L"Principe Diabolus Custom","DIABLOUS2","lsc_dlc_import_export","diablous2"},
{L"Principe Diabolus","DIABLOUS","",""},
{L"Dinka Double-T","DOUBLE","sssa_default","double"},
{L"Dinka Enduro","ENDURO","sssa_dlc_heist","enduro"},
{L"Pegassi Esskey","ESSKEY","sssa_dlc_biker","esskey"},
{L"Pegassi FCR 1000 Custom","FCR2","lsc_dlc_import_export","fcr2_b"},
{L"Pegassi FCR 1000","FCR","lsc_dlc_import_export","fcr2_a"},
{L"Pegassi Faggio Mod","FAGGIO3","sssa_dlc_biker","faggio3"},
{L"Pegassi Faggio","FAGGIO","sssa_default","faggio"},
{L"Pegassi Faggio Sport","FAGGIO2","sssa_dlc_biker","faggion"},
{L"Western Gargoyle","GARGOYLE","sssa_dlc_stunt","gargoyle"},
{L"Shitzu Hakuchou Dragbike","HAKUCHOU2","lgm_dlc_biker","hakuchou2"},
{L"Shitzu Hakuchou","HAKUCHOU","sssa_dlc_lts_creator","hakuchou"},
{L"LCC Hexer","HEXER","sssa_default","hexer"},
{L"LCC Innovation","INNOVATION","sssa_dlc_lts_creator","innovation"},
{L"Principe Lectro","LECTRO","lgm_dlc_heist","lectro"},
{L"Maibatsu Manchez","MANCHEZ","sssa_dlc_biker","manchez"},
{L"Principe Nemesis","NEMESIS","sssa_dlc_heist","nemesis"},
{L"Western Nightblade","NIGHTBLADE","sssa_dlc_biker","nightblade"},
{L"Opressor Mk II","Oppressor2","candc_battle","oppressor2"},
{L"Opressor Mk I","Oppressor","candc_gunrunning","oppressor"},
{L"PCJ 600","PCJ","sssa_default","pcj"},
{L"Western Ratbike","RATBIKE","sssa_dlc_biker","ratbike"},
{L"Western Rampant Rocket Tricycle","rrocket","lgm_dlc_vinewood","rrocket"},
{L"Pegassi Rufian","RUFFIAN","sssa_default","ruffian"},
{L"Maibatsu Sanchez","SANCHEZ2","sssa_default","sanchez2"},
{L"Maibatsu Sanchez Livery","SANCHEZ","sssa_default","sanchez"},
{L"LCC Sanctus","SANCTUS","sssa_dlc_biker","sanctus"},
{L"Nagasaki Shotaro","SHOTARO","lgm_dlc_biker","shotaro"},
{L"Western Sovereign","SOVEREIGN","",""},
{L"Nagasaki Stryder","stryder","lgm_dlc_casinoheist","stryder"},
{L"Dinka Thrust","THRUST","lgm_dlc_business2","thrust"},
{L"Shitzu Vader","VADER","sssa_default","vader"},
{L"Dinka Vindicator","VINDICATOR","lgm_dlc_luxe","vindicator"},
{L"Pegassi Vortex","VORTEX","sssa_dlc_biker","vortex"},
{L"Western Wolfsbane","WOLFSBANE","sssa_dlc_biker","wolfsbane"},
{L"Western Zombie Chopper","ZOMBIEB","sssa_dlc_biker","zombieb"},
{L"Western Zombie Bobber","ZOMBIEA","sssa_dlc_biker","zombiea"}
};
static std::vector<VehiclePreview> Military{
{L"HVY APC","apc","candc_gunrunning","apc"},
{L"Trailer","Trailersmall2","candc_gunrunning","trsmall2"},
{L"Barracks 3","Barracks3","",""},
{L"Barracks 2","Barracks","candc_default","barracks"},
{L"Barrage","barrage","candc_xmas2017","barrage_b"},
{L"Chernobog","chernobog","candc_xmas2017","chernobog_b"},
{L"Crusader","Crusader","candc_default","crusader"},
{L"Halftrack","halftrack","candc_gunrunning","halftrack"},
{L"Bangjali","khanjali","candc_xmas2017","khanjali_b"},
{L"Rhino","Rhino","candc_default","rhino"},
{L"HVY Scarab 1","SCARAB2","mba_vehicles","scarab2"},
{L"HVY Scarab 2","SCARAB3","mba_vehicles","scarab3"},
{L"HVY Scarab 3","SCARAB","mba_vehicles","scarab1"},
{L"Thruster","thruster","candc_xmas2017","thruster_b"},
{L"HVY Barracks 2","Barracks2","",""}
};
static std::vector<VehiclePreview> Emergency{
{L"Ambulans","Ambulance","",""},
{L"FIB","Fbi","",""},
{L"Damkar","Firetruk","",""},
{L"FIB SUV","Fbi2","",""},
{L"Lifeguard","Lguard","",""},
{L"Pranger","Pranger","",""},
{L"Polisi 3","Police3","",""},
{L"Cab Polisi","Policeb","",""},
{L"Polisi 2","Police2","",""},
{L"Polisi 1","Police","",""},
{L"Polisi tua 1","Policeold1","",""},
{L"Polisi tua 2","Policeold2","",""},
{L"Riot","Riot","",""},
{L"Policet","Policet","",""},
{L"Pbus","Pbus","candc_default","pbus"},
{L"Riot 2","riot2","candc_xmas2017","riot2_b"},
{L"Sheriff","Sheriff","",""},
{L"Sheriff SUV","Sheriff2","",""},
{L"Polisi 4","Police4","",""}
};
static std::vector<VehiclePreview> Service{
{L"Airbus","Airbus","candc_default","airbus"},
{L"MTL Brickade","Brickade","candc_executive1","brickade"},
{L"Bus","Bus","candc_default","bus"},
{L"Coach","Coach","candc_default","coach"},
{L"MTL Rally","Rallytruck","sssa_dlc_stunt","rallytruck"},
{L"pbus","Pbus2","sssa_dlc_battle","pbus2"},
{L"Rentbus","Rentalbus","candc_default","rentbus"},
{L"Taxi","Taxi","",""},
{L"Tourbus","Tourbus","",""},
{L"Trash","Trash2","",""},
{L"Trash 2","Trash","",""},
{L"MTL Wastelander","Wastelander","candc_importexport","wastlndr"},
};
static std::vector<VehiclePreview> Sedans{
{L"Declasse Asea Custom","Asea2","",""},
{L"Declasse Asea","Asea","sssa_dlc_business","asea"},
{L"Karin Asterope","Asterope","sssa_dlc_business","astrope"},
{L"Enus Cognoscenti 55","Cog55","lgm_dlc_apartments","cognosc"},
{L"Enus Cognoscenti 55 (Armored)","Cog552","",""},
{L"Declasse Premier","Premier","sssa_dlc_business","premier"},
{L"Emperor Modif 1 (破旧版)","Emperor2","",""},
{L"Emperor modif 2 (雪地版)","Emperor3","",""},
{L"Albany Emperor","Emperor","",""},
{L"Enus Super Diamond","Superd","sssa_default","superd"},
{L"Cheval Fugitive","Fugitive","sssa_default","fugitive"},
{L"Benefactor Glendale","Glendale","sssa_dlc_hipster","glendale"},
{L"Karin Intruder","Intruder","sssa_dlc_business","intruder"},
{L"Benefactor Turreted Limo","Limo2","",""},
{L"Dundreary Stretch","Stretch","sssa_default","stretch"},
{L"Albany Primo Custom","Primo2","",""},
{L"Albany Primo","Primo","sssa_dlc_hipster","primo"},
{L"Dundreary Regina","Regina","sssa_dlc_hipster","regina"},
{L"Mobil Jenazah","Romero","sssa_dlc_battle","Romero"},
{L"Benefactor Schafter V12 Armored","Schafter5","lgm_dlc_apartments","schafter3"},
{L"Benefactor Schafter LWB Armored","Schafter6","lgm_dlc_apartments","schafter4"},
{L"Benefactor Schafter","Schafter2","sssa_dlc_heist","schafter2"},
{L"Enus Stafford","Stafford","lgm_dlc_battle","stafford"},
{L"Vapid Stanier","Stanier","sssa_dlc_business","stanier"},
{L"Zirconium Stratum","Stratum","sssa_dlc_business","stratum"},
{L"Cheval Surge","Surge","sssa_dlc_heist","surge"},
{L"Obey Tailgater","Tailgater","sssa_dlc_hipster","tailgater"},
{L"Vulcar Ingot","Ingot","sssa_dlc_business","ingot"},
{L"Vulcar Warrener","Warrener","sssa_dlc_hipster","warrener"},
{L"Albany Washington","Washington","sssa_dlc_business","washingt"}
};
static std::vector<VehiclePreview> Industrial{
{L"HVY Bulldozer","Bulldozer","",""},
{L"HVY Cutter","Cutter","",""},
{L"Handler","Handler","",""},
{L"HVY Dump","Dump","candc_default","dump"},
{L"MTL Flatbed","Flatbed","",""},
{L"Guardian","Guardian","sssa_dlc_heist","guardian"},
{L"HVY Mixer2","Mixer2","",""},
{L"HVY Mixer","Mixer","",""},
{L"Rubble","Rubble","",""},
{L"Tiptruck 2","Tiptruck","",""},
{L"Tip Truck","Tiptruck2","",""}
};
static std::vector<VehiclePreview> Compacts{
{L"Asbo","asbo","sssa_dlc_casinoheist","asbo"},
{L"Dinka Blista","Blista","",""},
{L"Karin Dilettante (FlyUS)","Dilettante2","",""},
{L"Karin Dilettante","Dilettante","sssa_default","dilettan"},
{L"Grotti Brioso R/A","Brioso","sssa_dlc_stunt","brioso"},
{L"Weeny Issi Classic","issi3","sssa_dlc_assault","issi3"},
{L"Issi Apocalypse","ISSI4","mba_vehicles","issi3_c_1"},
{L"Issi Future Shock","ISSI5","mba_vehicles","issi3_c_2"},
{L"Issi Nightmare","ISSI6","mba_vehicles","issi3_c_3"},
{L"Dinka Blista Kanjo","kanjo","sssa_dlc_casinoheist","kanjo"},
{L"Benefactor Panto","Panto","sssa_dlc_hipster","panto"},
{L"Bollokan Prairie","Prairie","sssa_dlc_battle","prairie"},
{L"Declasse Rhapsody","Rhapsody","sssa_dlc_hipster","rhapsody"},
{L"Weeny Issi","Issi2","sssa_default","issi2"}
};
static std::vector<VehiclePreview>  Commercial{
{L"Vapid Benson","Benson","",""},
{L"MTL Future Shock Cerberus","CERBERUS2","mba_vehicles","cerberus2"},
{L"MTL Nightmare Cerberus","CERBERUS3","mba_vehicles","cerberus3"},
{L"MTL Appocalypse Cerberus","CERBERUS","mba_vehicles","cerberus1"},
{L"HVY Biff","Biff","",""},
{L"JoBuilt Hauler","Hauler","",""},
{L"JoBuilt Hauler Custom","Hauler2","candc_truck","cab_1"},
{L"MTL Packer","Packer","",""},
{L"Maibatsu Mule Custom","Mule2","",""},
{L"Maibatu Mule Custom1","Mule3","candc_default","mule3"},
{L"Maibatsu Mule Custom2","Mule4","candc_battle","mule4"},
{L"Maibatsu Mule","Mule","candc_default","mule"},
{L"JoBuilt Phantom Custom","phantom3","candc_truck","cab_0"},
{L"JoBuilt Phantom Wedge","Phantom2","candc_importexport","phantom2"},
{L"JoBuilt Phantom","Phantom","",""},
{L"MTL Pounder Custom","Pounder2","candc_battle","pounder2"},
{L"MTL Pounder","Pounder","",""},
{L"Stockade Custom","Stockade3","",""},
{L"Stockade","Stockade","",""},
{L"Terrobyte","Terbyte","",""}
};
static std::vector<VehiclePreview> Planes{
{L"Alpha Z1","alphaz1","elt_dlc_smuggler","alphaz1"},
{L"Avenger","avenger","candc_chopper","banner_5"},
{L"Avenger 2","avenger2","candc_chopper","banner_4"},
{L"Besra","Besra","elt_dlc_pilot","besra"},
{L"Blimp","Blimp2","",""},
{L"Blimp 2","Blimp","",""},
{L"Blimp 3","blimp3","elt_dlc_battle","blimp3"},
{L"RM-10 Bombushka","Bombushka","candc_smuggler","bombushka"},
{L"Antonov","Cargoplane","",""},
{L"Cuban 800","Cuban800","elt_default","cuban800"},
{L"Dodo","Dodo","elt_default","dodo"},
{L"Duster","Duster","elt_default","duster"},
{L"Howard NX-25","Howard","elt_dlc_smuggler","howard"},
{L"Hydra","Hydra","candc_default","hydra"},
{L"B747","Jet","",""},
{L"Luxor Deluxe","Luxor2","elt_dlc_executive1","luxor2"},
{L"Luxor","Luxor","elt_default","luxor"},
{L"Mammatus","Mammatus","elt_default","mammatus"},
{L"Microlight","Microlight","elt_dlc_smuggler","microlight"},
{L"Miljet","Miljet","elt_dlc_pilot","miljet"},
{L"Mogul","Mogul","candc_smuggler","mogul"},
{L"V-65 Molotok","Molotok","candc_smuggler","molotok_b"},
{L"Nimbus","Nimbus","elt_dlc_executive1","nimbus"},
{L"Nokota","Nokota","candc_smuggler","nokota"},
{L"P-996 Lazer","Lazer","candc_smuggler","lazer"},
{L"Pyro","Pyro","candc_smuggler","pyro"},
{L"Rogue","Rogue","candc_smuggler","rogue"},
{L"Seabreeze","Seabreeze","elt_dlc_smuggler","seabreeze"},
{L"Shamal","Shamal","elt_default","shamal"},
{L"LF-22 Starling","starling","candc_smuggler","starling"},
{L"B-11 Strikeforce","Strikeforce","candc_battle","strikeforce"},
{L"Stunt","Stunt","elt_default","stunt"},
{L"Titan","Titan","elt_default","titan"},
{L"Tula","tula","candc_smuggler","tula"},
{L"Velum","Velum2","elt_default","velum2"},
{L"Velum 2","Velum","elt_default","velum"},
{L"Vestra","Vestra","",""},
{L"Volatol (Kontol)","volatol","candc_xmas2017","volatol_b"}
};
static std::vector<VehiclePreview> Utility{
{L"Airtug","Airtug","",""},
{L"ArmyTrailer (1)","Armytrailer","",""},
{L"ArmyTrailer (2)","Armytrailer2","",""},
{L"ArmyTanker","Armytanker","",""},
{L"Trailer3","Tr3","",""},
{L"BoatTrailer","Boattrailer","",""},
{L"Caddy","Caddy","",""},
{L"Caddy2","Caddy2","foreclosures_bunker","transportation_2"},
{L"Caddy3","Caddy3","foreclosures_bunker","transportation_1"},
{L"Trailer2","Tr2","",""},
{L"Trailer4","Tr4","",""},
{L"Trailer (Pibwasser)","Trailers2","",""},
{L"Trailer (Big Good)","Trailers3","",""},
{L"Trailer4","Trailers4","",""},
{L"Dock Trailer","Docktrailer","",""},
{L"Dock Tug","Docktug","",""},
{L"TV Trailer (Fame or Shame)","Tvtrailer","",""},
{L"Tractor3","Tractor3","",""},
{L"Tractor2","Tractor2","",""},
{L"Freight Trailer","Freighttrailer","",""},
{L"Flat Trailer","Trflat","",""},
{L"HVY Forklift","Forklift","",""},
{L"Graintraler","Graintrailer","",""},
{L"Bale Trailer","Baletrailer","",""},
{L"Trailer Logs","Trailerlogs","",""},
{L"Prop Trailer","Proptrailer","",""},
{L"Trailer Larger","trailerlarge","candc_truck","banner_2"},
{L"Tanker","Tanker2","",""},
{L"Tanker(RON)","Tanker","",""},
{L"Ultility Truck","Utillitruck3","",""},
{L"Trailers","Trailers","",""},
{L"Ultility Truck 2","Utillitruck2","",""},
{L"Rake Trailer","Raketrailer","",""},
{L"Ripley","Ripley","",""},
{L"Scrap","Scrap","",""},
{L"Trailer Small","Trailersmall","",""},
{L"Mower","Mower","",""},
{L"Utility Truck 3","Utillitruck","",""},
{L"Tow Truck","Towtruck","",""},
{L"Tow Truck (2)","Towtruck2","",""},
{L"Tractor","Tractor","",""},
{L"Sadler 2","Sadler2","",""},
{L"Sadler","Sadler","sssa_default","sadler"},
};
static std::vector<VehiclePreview> Helicopters{
{L"Akula","akula","candc_xmas2017","akula_b"},
{L"Annihilator","Annihilator","elt_default","annihl"},
{L"Nagasaki Buzzard Attack Chopper","Buzzard","candc_default","buzzard"},
{L"Nagasaki Buzzard","Buzzard2","",""},
{L"Cargobob custom","Cargobob4","",""},
{L"Western Cargobob Jetsam","Cargobob2","",""},
{L"Western Cargobob (TPE)","Cargobob3","",""},
{L"Western Cargobob","Cargobob","candc_default","cargobob"},
{L"Frogger","Frogger","elt_default","frogger"},
{L"Frogger(FIB)","Frogger2","",""},
{L"Havok","havok","elt_dlc_smuggler","havok"},
{L"FH-1 Hunter","hunter","candc_smuggler","hunter"},
{L"Maverick","Maverick","elt_default","maverick"},
{L"Police Maverick","Polmav","",""},
{L"Savage","Savage","candc_default","savage"},
{L"Sea Sparrow","SEASPARROW","elt_dlc_assault","sparrow"},
{L"HVY Skylift","Skylift","",""},
{L"Buckingham Supervolito Carbon","Supervolito2","",""},
{L"Buckingham Supervolito","Supervolito","",""},
{L"Buckingham Swift Deluxe","Swift2","elt_dlc_executive1","swift2"},
{L"Buckingham Swift","Swift","elt_dlc_pilot","swift"},
{L"Valkyrie","Valkyrie2","",""},
{L"Valkyrie (Custom)","Valkyrie","candc_default","valkyrie"},
{L"Volatus","Volatus","elt_dlc_executive1","volatus"},
};
static std::vector<VehiclePreview> Vans{
{L"BF Surfer (Custom)","Surfer2","",""},
{L"BF Surfer","Surfer","sssa_dlc_hipster","surfer"},
{L"Bravado Bison (BackupRack)","Bison2","",""},
{L"Bravado Bison (Rack)","Bison3","",""},
{L"Bravado Bison","Bison","sssa_default","bison"},
{L"Bobcat XL","Bobcatxl","sssa_dlc_business","bobcatxl"},
{L"Boxville (armored)","Boxville5","candc_importexport","boxville5"},
{L"Boxville (Go Postal)","Boxville2","",""},
{L"Boxville (Humane)","Boxville3","",""},
{L"Boxville (Post OP)","Boxville4","candc_default","boxville4"},
{L"Boxville (W & P)","Boxville","",""},
{L"Brute Pony (Business)","Pony","",""},
{L"Brute Pony (Store)","Pony2","",""},
{L"Burrito (Bug Stars)","Burrito2","",""},
{L"Burrito (Construction)","Burrito4","",""},
{L"Burrito (Gang)","Gburrito2","sssa_dlc_heist","gburrito2"},
{L"Burrito (The Lost MC)","Gburrito","",""},
{L"Burriot 5","Burrito5","",""},
{L"Burrito 3","Burrito3","",""},
{L"Burrito (Graphics)","Burrito","",""},
{L"Camper","Camper","",""},
{L"Journey","Journey","candc_default","journey"},
{L"MiniVan Custom","Minivan2","lsc_lowrider2","minivan2_b"},
{L"MiniVAN","Minivan","sssa_dlc_business","minivan"},
{L"Paradise","Paradise","sssa_default","paradise"},
{L"Rumpo (Armored)","Rumpo3","sssa_dlc_executive_1","rumpo3_b"},
{L"Rumpo (Deludamol)","Rumpo2","",""},
{L"Rumpo (Weazel News)","Rumpo","sssa_dlc_heist","rumpo"},
{L"Speedo 3","Speedo4","",""},
{L"Speedo 2","Speedo2","",""},
{L"Speedo","Speedo","",""},
{L"Taco","Taco","",""},
{L"Bravado Youga Custom","Youga2","sssa_dlc_biker","youga2"},
{L"Bravado Youga","Youga","sssa_dlc_hipster","youga"}
};
static std::vector<VehiclePreview> Boats{
{L"Nagasaki Dinghy","Dinghy","",""},
{L"Nagasaki Dinghy (2-Seater)","Dinghy2","",""},
{L"Nagasaki Dinghy (Robbery)","Dinghy3","dock_default","dinghy3"},
{L"Nagasaki Dinghy (Black&White)","Dinghy4","",""},
{L"Shitzu Jetmax","Jetmax","dock_default","jetmax"},
{L"Dinka Marquis","Marquis","dock_default","marquis"},
{L"Police Predator","Predator","",""},
{L"Seashark","Seashark","dock_default","seashark"},
{L"Seashark (Lifeguard)","Seashark2","",""},
{L"Seashark (Charged)","Seashark3","",""},
{L"Pegassi Speeder","Speeder","dock_default","speeder"},
{L"Pegassi Speeder (Custom)","Speeder2","",""},
{L"Shitzu Squalo","Squalo","dock_default","squalo"},
{L"Submersible","Submersible","",""},
{L"Kraken Submersible (Kraken)","Submersible2","dock_default","sub2"},
{L"Shitzu Suntrap","Suntrap","dock_default","suntrap"},
{L"Lampadati Toro","Toro","dock_default","toro"},
{L"Lampadati Toro (Custom)","Toro2","",""},
{L"Shitzu Tropic","Tropic","dock_default","tropic"},
{L"Shitu Tropic (Custom)","Tropic2","",""},
{L"Tug","Tug","",""}
};
static std::vector<VehiclePreview> Cycles{
{L"BMX","Bmx","pandm_default","bmx"},
{L"Cruiser","Cruiser","pandm_default","cruiser"},
{L"Tribike2","Tribike2","pandm_default","tribike2"},
{L"Fixter","Fixter","",""},
{L"Scorcher","Scorcher","pandm_default","scorcher"},
{L"Tribike2","Tribike3","pandm_default","tribike3"},
{L"Tribike1","Tribike","pandm_default","tribike"}
};
static std::vector<VehiclePreview> Trains{
{L"CableCar","Cablecar","",""},
{L"Gerbong1","Freightcont1","",""},
{L"Gerbong2","Freightcont2","",""},
{L"Freightcar","Freightcar","",""},
{L"Freight","Freight","",""},
{L"Kereta Api","Freightgrain","",""},
{L"Metro Train","Metrotrain","",""},
{L"TankerCar","Tankercar","",""}
};
static std::vector<VehiclePreview> Trailer{
{L"Army Tanker", "Armytanker", "", "" },
{L"Army Trailer", "Armytrailer", "", "" },
{L"Army Trailer 2", "Armytrailer2", "", "" },
{L"Bale Trailer", "Baletrailer", "", "" },
{L"Boat Trailer", "Boattrailer", "", "" },
{L"Dock Trailer", "Docktrailer", "", "" },
{L"Freight Trailer", "Freighttrailer", "", "" },
{L"Grain Trailer", "Graintrailer", "", "" },
{L"Prop Trailer", "Proptrailer", "", "" },
{L"Rake Trailer", "Raketrailer", "", "" },
{L"Tanker (RON)", "Tanker", "", "" },
{L"Tanker (2)", "Tanker2", "", "" },
{L"Tanker (3)", "Tr2", "", "" },
{L"Tanker (4)", "Tr3", "", "" },
{L"Tanker (5)", "Tr4", "", "" },
{L"Trailer Logs", "Trailerlogs", "", "" },
{L"Trailer entah", "Trailers", "", "" },
{L"Trailer (Pibwasser)", "Trailers2", "", "" },
{L"Trailer (Big Goods)", "Trailers3", "", "" },
{L"Trailer 4", "Trailers4", "", "" },
{L"Trailer Small", "Trailersmall", "", "" },
{L"Trailer Large", "trailerlarge", "", "" },
{L"Trailer Flat", "Trflat", "", "" },
{L"TV Trailer (Fame or Shame)", "Tvtrailer", "", "" }
};
static std::vector<VehiclePreview> SUV{
{L"Gallivanter Baller (CEO)","Baller6","",""},
{L"Gallivanter Baller 2","Baller2","sssa_default","baller2"},
{L"Gallivanter Baller LE (Armored)","Baller5","",""},
{L"Gallivanter Baller LE LWB","Baller4","lgm_dlc_apartments","baller4"},
{L"Gallivanter Baller LE","Baller3","lgm_dlc_apartments","baller3"},
{L"Gallivanter Baller","Baller","",""},
{L"BeeJay XL","Bjxl","sssa_dlc_battle","bjxl"},
{L"Canis Seminole Frontier","Seminole","sssa_dlc_heist","seminole"},
{L"Albany Cavalcade Mk2","CAVALCADE2","sssa_dlc_business","cavcade2"},
{L"Albany Cavalcade","CAVALCADE","sssa_default","cavcade"},
{L"Vapid Contender","Contender","sssa_dlc_stunt","contender"},
{L"Benefactor Dubsta2","Dubsta2","",""},
{L"Benefactor Dubsta","Dubsta","",""},
{L"Emperor Habanero","Habanero","sssa_dlc_battle","habanero"},
{L"Enus Huntley S","Huntley","lgm_dlc_business2","huntley"},
{L"Fathom FQ 2","fq2","sssa_dlc_battle","fq2"},
{L"Declasse Granger","Granger","sssa_dlc_business","granger"},
{L"Bravado Gresley","Gresley","sssa_dlc_heist","gresley"},
{L"Dundreary Landstalker","Landstalker","sssa_dlc_heist","landstalker"},
{L"Mammoth Patriot","Patriot","sssa_dlc_battle","patriot"},
{L"Cannis Mesa (Custom)","Mesa2","",""},
{L"Cannis Mesa SUV","Mesa","candc_default","mesa"},
{L"Lampadati Novak","novak","lgm_dlc_vinewood","novak"},
{L"Mammoth Patriot Stretch","Patriot2","sssa_dlc_battle","patriot2"},
{L"Vapid Radius","Radi","sssa_dlc_business","radi"},
{L"Ubermacht Rebla GTS","rebla","lgm_dlc_casinoheist","rebla"},
{L"Obey Rocoto","Rocoto","sssa_default","rocoto"},
{L"Benefactor Serrano","Serrano","sssa_dlc_battle","serrano"},
{L"Pegassi Toros","TOROS","lgm_dlc_arena","toros"},
{L"Benefactor XLS(Armored)","Xls2","",""},
{L"Benefactor XLS","Xls","lgm_dlc_executive1","xls"}
};
static std::vector<std::pair<std::wstring, std::vector<VehiclePreview>>> vehiclePreview{
	{L"Super >>",Super},
	{L"Sport >>",Sports},
	{L"SportClassic >>",SportsClassics},
	{L"Coupe >>",Coupes},
	{L"Muscle >>",Muscle},
	{L"Offroad >>",Offroad},
	{L"Motor >>",Motorcycles},
	{L"Militer >>",Military},
	{L"Emergency >>",Emergency},
	{L"Service >>",Service},
	{L"Sedan >>",Sedans},
	{L"Industri >>",Industrial},
	{L"Compact >>",Compacts},
	{L"Commercial >>",Commercial},
	{L"Pesawat >>",Planes},
	{L"Utility >>",Utility},
	{L"Helikopter >>",Helicopters},
	{L"Van >>",Vans},
	{L"Perahu >>",Boats},
	{L"Sepeda >>",Cycles},
	{L"Kereta >>",Trains},
	{L"Trailer >>",Trailer},
	{L"SUV >>",SUV},
};


static unsigned int joaat(std::string input)
{
	unsigned int num1 = 0U;
	for (char c : input)
	{
		unsigned int num2 = num1 + (unsigned int)tolower(c);
		unsigned int num3 = num2 + (num2 << 10);
		num1 = num3 ^ num3 >> 6;
	}
	unsigned int num4 = num1 + (num1 << 3);
	unsigned int num5 = num4 ^ num4 >> 11;
	return num5 + (num5 << 15);
}
